### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Gcamara14** [Commerce7/Integration#2]
Hey C7 Team,

The quick shop item in your documentation is missing a closing div. In addition, the first div has a trailing slash.

URL: https://github.com/Commerce7/Design-Integration/wiki/01.-Widgets#create-a-quick-shop-page-with-a-list-of-products

**Here's a fix:**

`<div id="c7-quick-shop" data-collection-slug="slug"></div>`

**Comment by andrewkamphuis** [comment]
Thank you.  This has been adjusted.
