### ISSUE TITLE
HTML issues in subscribe widget 

### ISSUE THREAD

**Issue by ecupaio** [Commerce7/Integration#3]
The subscribe widget injects the input tag within the label tag and does not provide a class for parent container which makes custom styling for the fields impossible. 

```
<form class="c7-form" method="post">
  <div class="">
     <label for="c7-email">Email <input type="text" id="c7-email" name="email" autocomplete="email" value=""></label>
  </div>
  <div class="c7-form__button-row">
    <button type="submit" class="c7-button">Submit</button>
  </div>
</form>
```

**Comment by michaelbourne** [comment]
Assuming you have control of where it goes, just target a parent class in your theme.

```
.footer label[for=c7-email]
{
    /* ...definitions here... */
}

.footer #c7-email {
    /* ...definitions here... */
}

.footer #c7-button {
    /* ...definitions here... */
}
```

**Comment by ecupaio** [comment]
yeah but the input tag is INSIDE of the label tag. so I can't say, add `display: block` so the label sits next to the input when I have display flex on the parent. 

Big picture, get the input tag outside of the label tag.

**Comment by michaelbourne** [comment]
What exactly are you trying to do that's not possible with nested elements? (which is valid html)

**Comment by ecupaio** [comment]
I found a way use an API call to add subscribers so I just won't use your widget. Though, your API documentation doesn't say any of the structured data that can be sent to the `customer/subscribe` endpoint. I was just able to use DevTools to see what was being sent.

**Comment by ecupaio** [comment]
just updated to the design integration to v2 and now the label and input elements are now separate elements as they should be.
